### ISSUE TITLE
python errors out when launching mcc.py

### ISSUE THREAD

**Issue by codingglitch** [simon816/Command-Block-Assembly#14]
When I tried the example command for fib.asm, python errors out with an invalid syntax error. Weirdly enough, it's from cbl.compiler :
line 336
assert not decl.async
                               ^
SyntaxError: invalid syntax

**Comment by codingglitch** [comment]
![MCCError](https://user-images.githubusercontent.com/47162074/77256659-61a9fa80-6c4e-11ea-994a-e9033ce7f30d.JPG)

**Comment by simon816** [comment]
I see. In Python 3.7, "async" was made a reserved keyword, therefore my use of it as a variable name is no longer valid. I have Python 3.6 installed so had not observed this myself.
I will fix it soon. Thanks.

**Comment by codingglitch** [comment]
Just so you know, you should update python : their is probably other things that changed and that could break mcc.

**Comment by simon816** [comment]
It's because I'm using Ubuntu 18.04 where the `python3` package is currently [3.6.7](https://packages.ubuntu.com/bionic-updates/python3). New LTS in a month will be [3.8](https://packages.ubuntu.com/focal/python3). I could set up some sort of CI for multiple versions and have unit tests, but haven't spent the additional effort setting that up thus far :)

**Comment by simon816** [comment]
Should be fixed now.
